micronaut:
  application:
    name: eyalgo-demo
  health:
    monitor:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"

endpoints:
  health:
    enabled: true
    details-visible: anonymous
    disk-space:
      enabled: true
    jdbc:
      enabled: true

jpa:
  enabled: false

datasources:
  default:
    db-type: "postgres"
    dialect: "POSTGRES"
    driverClassName: 'org.postgresql.Drive'

liquibase:
  enabled: true
  datasources:
    default:
      liquibase-schema: "PUBLIC"
      change-log: 'classpath:db/liquibase-changelog.xml'
