datasources:
  default:
    db-type: "mysql"
    url: 'tcp://'
    username: 'admin'
    password: 'admin'
    dialect: 'MYSQL'
    driverClassName: 'com.mysql.cj.jdbc.Driver'

flyway:
  datasources:
    default:
      locations:
        - classpath:databasemigrations/mysql
