datasources:
  default:
    db-type: "postgres"
    url: 'tcp://'
    username: 'admin'
    password: 'admin'
    dialect: 'POSTGRES'
    driverClassName: 'org.postgresql.Driver'

flyway:
  datasources:
    default:
      locations:
        - classpath:databasemigrations/postgres
