micronaut:
  application:
    name: eyalgo-demo
  health:
    monitor:
      enabled: true

endpoints:
  health:
    enabled: true
    details-visible: anonymous
    disk-space:
      enabled: true
    jdbc:
      enabled: true
    flyway:
      enabled: true
      details-visible: anonymous
