micronaut:
  application:
    name: eyalgo-demo
  health:
    monitor:
      enabled: true
  metrics:
    enabled: true
    binders:
      web:
        enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: anonymous
    disk-space:
      enabled: true
    jdbc:
      enabled: true
  beans:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
  flyway:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  routes:
    enabled: true
    sensitive: false
  loggers:
    enabled: true
    sensitive: false

jpa:
  enabled: false

datasources:
  default:
    db-type: "h2"
    url: 'jdbc:h2:mem:PUBLIC;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE'
    username: 'sa'
    password: ''
    dialect: 'H2'
    driverClassName: 'org.h2.Driver'

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:databasemigrations

info:
  demo:
    description: "Demo application"
