micronaut:
  application:
    name: eyalgo-demo
  health:
    monitor:
      enabled: true

endpoints:
  health:
    enabled: true
    details-visible: anonymous
    disk-space:
      enabled: true
    jdbc:
      enabled: true

datasources:
  default:
    url: 'jdbc:h2:mem:test;SCHEMA=PUBLIC;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'

liquibase:
  enabled: true
  datasources:
    default:
      liquibase-schema: "PUBLIC"
      change-log: 'classpath:db/liquibase-changelog.xml'
