micronaut:
  application:
    name: eyalgo-demo
  health:
    monitor:
      enabled: true

endpoints:
  health:
    enabled: true
    details-visible: anonymous
    disk-space:
      enabled: true
    jdbc:
      enabled: true
    flyway:
      enabled: true
      details-visible: anonymous

datasources:
  default:
    url: 'jdbc:h2:mem:test;SCHEMA=PUBLIC;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'

jpa:
  default:
    packages-to-scan:
      - 'eyalgo.demo.adapters.data'
      - 'eyalgo.demo.adapters.data.exposed'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

liquibase:
  enabled: true
  datasources:
    default:
      liquibase-schema: "PUBLIC"
      change-log: 'classpath:db/liquibase-changelog.xml'
#      default-schema: "eyalgo-demo"
