micronaut:
  application:
    name: eyalgo-demo
  health:
    monitor:
      enabled: true
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"

endpoints:
  health:
    enabled: true
    details-visible: anonymous
    disk-space:
      enabled: true
    jdbc:
      enabled: true
      sensitive: false
    beans:
      enabled: true
      sensitive: false
    info:
      enabled: true
      sensitive: false

jpa:
  enabled: false

datasources:
  default:
    db-type: "h2"
    url: 'jdbc:h2:mem:liquibaseDisabledDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE'
    username: 'sa'
    password: ''
    dialect: 'H2'
    driverClassName: 'org.h2.Driver'

liquibase:
  enabled: true
  datasources:
    default:
      liquibase-schema: "PUBLIC"
      change-log: 'classpath:db/liquibase-changelog.xml'
