micronaut:
  application:
    name: eyalgo-demo
  health:
    monitor:
      enabled: true
  metrics:
    enabled: true
    binders:
      web:
        enabled: true
  caches:
    guests:
      charset: UTF-8
  jms:
    activemq:
      classic:
        enabled: true
        connection-string: 'tcp://localhost:61616'

flyway:
  datasources:
    default:
      enabled: true

endpoints:
  env:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
    details-visible: anonymous
    disk-space:
      enabled: true
    jdbc:
      enabled: true
  beans:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
  flyway:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  routes:
    enabled: true
    sensitive: false
  loggers:
    enabled: true
    sensitive: false
  caches:
    enabled: true
    sensitive: false

jpa:
  enabled: false

info:
  demo:
    description: "Demo application"

solace:
  url: "amqp://localhost:5672"
  user: "admin"
  password: "admin"
